/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as CallStudioRouteImport } from './routes/call-studio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrivacyRouteImport } from './routes/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const CallStudioRoute = CallStudioRouteImport.update({
  id: '/call-studio',
  path: '/call-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/call-studio': typeof CallStudioRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/call-studio': typeof CallStudioRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/call-studio': typeof CallStudioRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api-reference' | '/call-studio' | '/contact' | '/docs' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api-reference' | '/call-studio' | '/contact' | '/docs' | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/call-studio'
    | '/contact'
    | '/docs'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  CallStudioRoute: typeof CallStudioRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-studio': {
      id: '/call-studio'
      path: '/call-studio'
      fullPath: '/call-studio'
      preLoaderRoute: typeof CallStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  CallStudioRoute: CallStudioRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
